# .github/workflows/deploy.yml
name: Build and deploy Vite app to Azure Web App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  BUILD_DIR: dist

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'    # Node 20 LTS is safe for Vite 5
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: vite-build
          path: ${{ env.BUILD_DIR }}    # 👈 upload ONLY dist/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: vite-build
          path: ./dist                  # download into ./dist

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_5B951500C6D4455F96D680430A2FE3F3 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_DAB6D32D71914B7C9568E255A35F160A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_225148546A4A43789652EE3D43FD3C38 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'TBI-CO2-Credit-Portal'
          slot-name: 'production'
          package: ./dist               # 👈 deploy ONLY dist/
